### ISSUE TITLE
Clickable component change causing crash

### ISSUE THREAD

**Issue by asportnoy** [WolfPlugs/GlobalBadges#3]
A change with the `Clickable` component broke the existing queries. You can see the query I used to fix it in Replugged
[here](https://github.com/replugged-org/replugged/blob/de3aab63b5cab5103e1220f5b66f3068a9a54996/src/renderer/modules/components/Clickable.tsx#L13-L15).

This will be added to common components in the next release, but this issue makes the plugin unusable since it crashes any time you open the profile, so I think you should implement this temporarily.

**Comment by Wolfkid200444** [comment]
Thanks for the head up this change was implimented right here https://github.com/WolfPlugs/GlobalBadges/blob/ff76cf5661816ca18c6a603502df5eabed2eba22/src/customBadges.tsx#L43-L48
