### ISSUE TITLE
crash when attempting to render badges

### ISSUE THREAD

**Issue by Penguin-Spy** [WolfPlugs/GlobalBadges#5]
anywhere discord tries to render a user's badges (profile popout, user status popout thingy, or account settings) the plugin crashes discord:
`TypeError: Cannot read properties of undefined (reading '97399302313242624')`
`    at Q (renderer.js?t=1699000114649:1:27091)`
`    at renderer.js?t=1699000114649:1:25053`

the stack trace points to [line 232 of index.tsx in getBadgeselements()](https://github.com/WolfPlugs/GlobalBadges/blob/5361b3b1b24c26f53f3b5609683b6a25b32e84aa/src/index.tsx#L232C31-L232C35).
i'm using the latest version (v1.3.3)

**Comment by Wolfkid200444** [comment]
This should be fixed now
